### ISSUE TITLE
Fix None type issues in reading input definitions

### ISSUE THREAD

**Issue by sjboeing** [EUREC4A-UK/lagtraj#112]
```bash
python -m lagtraj.trajectory.create lagtraj://eurec4a_20200205_12_eul
Running with numba
Traceback (most recent call last):
  File "/home/stevenboeing/miniconda2/envs/py3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/stevenboeing/miniconda2/envs/py3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/stevenboeing/lagtraj_temp/lagtraj/lagtraj/trajectory/create.py", line 344, in <module>
    main()
  File "/home/stevenboeing/lagtraj_temp/lagtraj/lagtraj/trajectory/create.py", line 81, in main
    cli(data_path=args.data_path, trajectory_name=args.trajectory)
  File "/home/stevenboeing/lagtraj_temp/lagtraj/lagtraj/trajectory/create.py", line 89, in cli
    trajectory_definition=traj_definition, root_data_path=data_path
  File "/home/stevenboeing/lagtraj_temp/lagtraj/lagtraj/trajectory/create.py", line 138, in _get_times_from_domain
    root_data_path=root_data_path, domain_name=trajectory_definition.domain
  File "/home/stevenboeing/lagtraj_temp/lagtraj/lagtraj/domain/download.py", line 78, in download_complete
    domain_params = load_definition(domain_name=domain_name, data_path=root_data_path)
  File "/home/stevenboeing/lagtraj_temp/lagtraj/lagtraj/domain/load.py", line 12, in load_definition
    required_fields=INPUT_REQUIRED_FIELDS,
  File "/home/stevenboeing/lagtraj_temp/lagtraj/lagtraj/input_definitions/load.py", line 47, in load_definition
    requesting_lagtraj_bundled_input = input_name.startswith(
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by leifdenby** [comment]
Ah yes, this makes sense. The code is attempting to check if all domain data is downloaded, but for an Eulerian trajectory no domain is given. So there's no domain definition to load. This is an easy fix.

I could add a test which runs Eulerian trajectory creation and forcing creation via the CLI (I'm adding that for the Lagrangian trajectories and forcings right now: https://github.com/EUREC4A-UK/lagtraj/pull/113), but that will just take a bit of refactoring of the testing code.

**Comment by sjboeing** [comment]
@leif: this is actually a useful bug. Currently, when creating a Eulerian trajectory, we are no longer using the domain. But the domain is needed to get the domain times for the trajectory. Proposed fix is to load the domain data after all.
