### ISSUE TITLE
Issues running master branch with numba

### ISSUE THREAD

**Issue by sjboeing** [EUREC4A-UK/lagtraj#24]
Hi @leifdenby,

I am currently having issues running the master branch on the trajectory I usually use with numba. This shows up with the error below. The issue seems to be that the heights array used by calculate_heights_and_pressures still has the vertical coordinate in. This might mean it has been dropped from the wrong dataset (it needs to be a 2d field), I will check for you.
___________________
Traceback (most recent call last):
  File "/home/stevenboeing/miniconda2/envs/py3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/stevenboeing/miniconda2/envs/py3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/stevenboeing/lagtraj_leif/lagtraj/lagtraj/trajectory/create.py", line 273, in <module>
    main()
  File "/home/stevenboeing/lagtraj_leif/lagtraj/lagtraj/trajectory/create.py", line 67, in main
    cli(data_path=args.data_path, trajectory_name=args.trajectory)
  File "/home/stevenboeing/lagtraj_leif/lagtraj/lagtraj/trajectory/create.py", line 100, in cli
    ds_trajectory = create_trajectory(**kwargs)
  File "/home/stevenboeing/lagtraj_leif/lagtraj/lagtraj/trajectory/create.py", line 50, in create_trajectory
    return create_lagrangian_trajectory(origin=origin, da_times=da_times, **kwargs)
  File "/home/stevenboeing/lagtraj_leif/lagtraj/lagtraj/trajectory/create.py", line 222, in create_lagrangian_trajectory
    origin=origin, da_times=da_times, extrapolation_func=extrapolation_func
  File "/home/stevenboeing/lagtraj_leif/lagtraj/lagtraj/trajectory/create.py", line 254, in _create_extrapolated_trajectory
    lat=points[-1].lat, lon=points[-1].lon, dt=dt, t0=ds_prev_posn.time
  File "/home/stevenboeing/lagtraj_leif/lagtraj/lagtraj/trajectory/create.py", line 218, in extrapolation_func
    velocity_method_kwargs=velocity_method_kwargs,
  File "/home/stevenboeing/lagtraj_leif/lagtraj/lagtraj/trajectory/extrapolation.py", line 79, in extrapolate_using_domain_data
    **velocity_method_kwargs
  File "/home/stevenboeing/lagtraj_leif/lagtraj/lagtraj/trajectory/integration/velocity_estimation.py", line 47, in estimate_horizontal_velocities
    u_traj, v_traj = velocity_at_height(ds_column, **kwargs)
  File "/home/stevenboeing/lagtraj_leif/lagtraj/lagtraj/trajectory/integration/velocity_estimation.py", line 25, in velocity_at_height
    ds_on_height_level = interpolate_to_height_levels(ds_column, height)
  File "/home/stevenboeing/lagtraj_leif/lagtraj/lagtraj/domain/sources/era5/interpolation.py", line 15, in interpolate_to_height_levels
    ds_extra = calculate_heights_and_pressures(ds_model_levels)
  File "/home/stevenboeing/lagtraj_leif/lagtraj/lagtraj/domain/sources/era5/utils.py", line 99, in calculate_heights_and_pressures
    p_surf, height_surf, a_coeffs_137, b_coeffs_137, t_field, q_field,
  File "/home/stevenboeing/miniconda2/envs/py3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/stevenboeing/miniconda2/envs/py3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/home/stevenboeing/miniconda2/envs/py3/lib/python3.7/site-packages/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function setitem>) with argument(s) of type(s): (array(float64, 3d, C), UniTuple(int64 x 3), array(float64, 1d, C))
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
In definition 6:
    All templates rejected with literals.
In definition 7:
    All templates rejected without literals.
In definition 8:
    All templates rejected with literals.
In definition 9:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of setitem at /home/stevenboeing/lagtraj_leif/lagtraj/lagtraj/domain/sources/era5/utils.py (42)

File "lagtraj/domain/sources/era5/utils.py", line 42:
def _calculate_heights_and_pressures(
    <source elided>
            z_s = height_surf[j, i]
            height_h[k_max - 1, j, i] = z_s

**Comment by sjboeing** [comment]
Think I have a fix (needed to solve a another issue as well), will send a pull request soon.

**Comment by leifdenby** [comment]
thanks for the fix @sjboeing! Should we close this? I think this was fixed with https://github.com/EUREC4A-UK/lagtraj/pull/25, right?
